version: "3.7"

networks:
  traefik_public:
    external: true

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "10m" 

services:
  ipx:
    <<: *default-opts
    build: 
      context: .
      target: ipx
      tags:
        - "ipx:lastest"
    image: ipx
    networks:
      - traefik_public
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - IPX_HTTP_DOMAINS=files.vandal.services
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.ipx-rtr.rule=Host(`ipx.vandal.services`)"
      - "traefik.http.routers.ipx-rtr.entrypoints=websecure"
      - "traefik.http.services.ipx-svc.loadbalancer.server.port=3000"
      - "traefik.http.routers.ipx-rtr.service=ipx-svc"
      - "traefik.http.routers.ipx-rtr.tls=true"
      - "traefik.http.routers.ipx-rtr.middlewares=secure-headers@file,cloudflare-ipwhitelist@file,real-ip@file"