// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  CF_PAGES_URL?: string
  CF_PAGES_BRANCH?: string
  BASE_URL?: string
}
